design:
  theme: sb2nov
  page:
    size: a4
    top_margin: 0.50in
    bottom_margin: 0.50in
    left_margin: 0.55in
    right_margin: 0.55in
    show_footer: false
    show_top_note: false
  typography:
    line_spacing: 0.60em
    alignment: left
    font_family: Source Sans 3
    font_size:
      body: 10pt
      name: 22pt
      headline: 10.8pt
      connections: 9.6pt
      section_titles: 1.15em
  links:
    underline: false
    show_external_link_icon: false
  header:
    alignment: left
    space_below_name: 0.18cm
    space_below_headline: 0.15cm
    space_below_connections: 0.30cm
    connections:
      show_icons: false
  section_titles:
    type: with_full_line
    line_thickness: 0.4pt
    space_above: 0.32cm
    space_below: 0.16cm
  sections:
    allow_page_break: true
    space_between_regular_entries: 0.45em
    space_between_text_based_entries: 0.24em
    show_time_spans_in: []
